<?php
/**
 * Implementation of hook_node_view_alter(&$build)
 */
function kit_menu() {
	$items['kit/new'] = array(
	  'title' => t('Request a new kit'),
	  'page callback' => 'kit_new_page',
	  'access arguments' => array('access content'), 
	  'type' => MENU_CALLBACK,
	);
//	$items['kit/detail/%'] = array(
//	  'title' => t('Kit Details'),
//	  'page callback' => 'kit_view',
//	  'page arguments' => array(1),
//	  'access arguments' => array('access content'), 
//	  'type' => MENU_CALLBACK,
//	);
	return $items;
}

function kit_new_page() {
	global $user;
	$user = user_load($user->uid);
		
	$rows = array(
		array(t('First Name'), $user->field_first_name['und'][0]['safe_value']),
		array(t('Last Name'), $user->field_last_name['und'][0]['safe_value']),
		array(t('Address'), $user->field_address['und'][0]['safe_value']),
		array(t('City / State / Zip'), $user->field_city_state_zip['und'][0]['safe_value']),
		array(t('Phone'), $user->field_phone['und'][0]['safe_value']),
	);
	$output = theme('table', array('header' => array('Shipping Information',''), 'rows' => $rows));
	
	$output .= drupal_render(drupal_get_form('kit_newform'));	
		
	return $output;
}

function kit_view() {

}

function kit_newform($form, &$form_state) {
	$form['description'] = array(
		'#type' => 'textarea',
		'#title' => t('Description of metals'),
		'#required' => true,
		'#description' => t("Enter a description of the metals you'll be sending us.")
	);
	$form['kit_type'] = array(
		'#type' => 'checkboxes',
		'#title' => t('Types of Metal'),
		'#required' => true,
		'#options' => drupal_map_assoc( array(t('gold'), t('platinum'), t('silver'), t('other')) ),
	);
	$form['submit'] = array(
		'#type' => 'submit', 
		'#value' => t('Save'),
		'#submit' => array('kit_new_submit'),
	);
	return $form;
}

function kit_user_form($form, &$form_state) {
	
	$form['description'] = array(
		'#type' => 'textarea',
		'#title' => t('Description of metals'),
		'#required' => true,
		'#description' => t("Enter a description of the metals you'll be sending us.")
	);
	$form['kit_type'] = array(
		'#type' => 'checkboxes',
		'#title' => t('Types of Metal'),
		'#required' => true,
		'#options' => drupal_map_assoc( array(t('gold'), t('platinum'), t('silver'), t('other')) ),
	);
	$form['submit'] = array(
		'#type' => 'submit', 
		'#value' => t('Save'),
		'#submit' => array('kit_user_reg_submit'),
	);
	return $form;
}

function kit_new_validate($form, &$form_state) {
	drupal_set_message('Form validate.', 'status');
}

function kit_new_submit($form, &$form_state) {	
	global $user;
	kit_save($form_state, $user->uid);
}

/**
  * Implementation of kit_save
 **/
function kit_save($form, $uid) {
 	$kit = (object) NULL;
	$kit->type = 'kit';
	$kit->uid = $uid;
	$kit->created = strtotime("now");
	$kit->changed = strtotime("now");
	$kit->status = 1;
	$kit->promote = 0;
	$kit->moderate = 0;
	$kit->sticky = 0;
	$kit->language = 'und';
	$kit->title = 'Sample';
	
	$kit->field_user['und'][0]['target_id'] = $uid;
	$kit->field_status['und'][0]['value'] = 'Requested';
	
	$metals = array();
	foreach($form['values']['kit_type'] as $key => $value) {
		if($value !== 0) {
			$metals[] = array('value' => $value);
		}
	}
	
	$kit->field_types_of_metal['und'] = $metals;
	
	$kit->body['und'][0]['value'] = $form['values']['description'];
	
	node_object_prepare($kit);
	
	node_save($kit);

	drupal_set_message('Kit requested!', 'status');
 }


/**
  * Implementation of hook_form_alter
 **/
function kit_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'user_register_form') {
		
		$form['kit_type'] = array(
			'#type' => 'checkboxes',
			'#title' => t('Types of Metal'),
			'#required' => true,
			'#options' => drupal_map_assoc( array(t('gold'), t('platinum'), t('silver'), t('other')) ),
			'#weight' => 20
		);
		
		$form['kit_description'] = array(
			'#type' => 'textarea',
			'#title' => t('Description'),
			'#required' => true,
			'#weight' => 30,
		);
		$form['#submit'][] = 'kit_user_reg_submit';
	}
}

/**
  * Custom submit handler
  */
function kit_user_reg_submit($form, &$form_state) {
	
}

function kit_block_info() {
	$blocks['kit_user_register'] = array(
		'info'	=>	t('Kit: User Registration')
	);
	
	return $blocks;
}

function kit_block_view($delta = '') {
	if($delta == 'kit_user_register') {
		$block['content'] = drupal_render(drupal_get_form('kit_user_form'));
	}
	return $block;
}